version: "3.0"

services:
    account.com:
        container_name: "mock-idp"
        build:
            context: ./idp
            args:
                - PORT=8001
        restart: always
        tty: true
        ports:
            - 8001:8001
    ws1:
        container_name: "webservice1"
        build:
            context: ./webservice
            args:
                - PORT=8002
        restart: always
        tty: true
        ports:
            - 8002:8002
    ws2:
        container_name: "webservice2"
        build:
            context: ./webservice
            args:
                - PORT=8003
        restart: always
        tty: true
        ports:
            - 8003:8003


